open: false
lots:
  site-eight:
    about: Description
    date-first: 2019-12-20T18:54:12.265Z
    date-last: 2019-12-20T18:54:12.290Z
    display: true
  site-five:
    about: Description
    date-first: 2019-12-20T18:54:12.088Z
    date-last: 2019-12-20T18:54:12.116Z
    display: true
  site-four:
    about: Description Site 4
    date-first: 2019-12-09T18:54:12.024Z
    date-last: 2019-12-19T18:54:12.055Z
    display: true
  site-one:
    about: Site one description
    date-first: 2019-12-01T18:54:11.825Z
    date-last: 2019-12-07T18:54:11.863Z
    display: true
  site-seven:
    about: Site7
    date-first: 2019-12-20T18:54:12.194Z
    date-last: 2019-12-20T18:54:12.225Z
    display: false
  site-six:
    about: Site 6
    date-first: 2019-12-20T18:54:12.144Z
    date-last: 2019-12-20T18:54:12.170Z
    display: false
  site-three:
    about: Site 3 description
    date-first: 2019-12-08T18:54:11.970Z
    date-last: 2019-12-14T18:54:11.997Z
    display: true
  site-two:
    about: Site 2 description
    date-first: 2019-12-02T18:54:11.893Z
    date-last: 2019-12-06T18:54:11.927Z
    display: true
