open: true
lots:
  site one:
    about: Check out our favorite hookup site today!
    date-first: 2019-11-29T17:00:26.240Z
    date-last: 2019-11-26T17:00:00.000Z
  site two:
    about: site 2 is not as good
    date-first: 2019-11-24T17:09:07.692Z
    date-last: 2019-11-25T17:09:07.729Z
