# config.yml
backend:
 name: git-gateway
 branch: master # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'
media_library:
  name: 'media_library'

collections:
 - name: 'pages'
   label: 'Pages'
   files:
     - label: "Page data"
       name: "pages"
       file: "_data/pages.yml"
       fields:
        - label: "Pages"
          name: 'pages'
          widget: 'object'
          fields:
             - label: "Homeowner Page"
               name: "homeowner-page" 
               widget: 'object'
               fields:
                 - {label: "Article-Title", name: "article-title", widget: "string"}
                 - {label: "Article-Text", name: "article-text", widget: "text"}
                 - {label: "Description Title", name: "description-title", widget: "string"}
                 - {label: "Description", name: "description", widget: "text"}
                 - {default: "Site 1", name: "textname", widget: "hidden"}
                 - {label: "List", name: "list", widget: "list", field: {label: "label1", name: "name1", widget: "string"}}
                 - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
                 - {label: "Image", name: "image", widget: "file", default: "/assets/uploads/pic3.jpg", required: false}
             - label: "About Page"
               name: "about-page" 
               widget: 'object'
               fields:
                 - {label: "About Page", name: "about", widget: ""}
             - label: "FAQ's Page"
               name: "faq-page" 
               widget: 'object'
               fields:
                 - {label: "FAQ's", name: "faq", widget: ""}
               
