# config.yml
backend:
 name: git-gateway
 branch: master # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'
media_library:
  name: 'media_library'

collections:
 - name: 'sites'
   label: 'Sites'
   files:
     - label: "Site data"
       name: "sites"
       file: "_data/site.yml"
       fields:
 #  - name: 'sites'
 #    label: 'Sites'
 #    folder: "_data/"
 #    file: "site.yml" 
 #    fields:
        - {label: 'Open or Not', name: 'open', widget: 'boolean'}
        - label: "Sites"
          name: 'lots'
          widget: 'object'
          fields:
             - label: "Site 1"
               name: "site one" 
               widget: 'object'
               fields:
                 - {label: "Earliest Date", name: "date-first", widget: "datetime"}
                 - {label: "Latest Date", name: "date-last", widget: "datetime"}
                 - {label: "description", name: "about", widget: "string"}
                 - {default: "Site 1", name: "textname", widget: "hidden"}
                 - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
             - label: "Site 2"
               name: "site two" 
               widget: 'object'
               fields:
                 - {label: "Earliest Date", name: "date-first", widget: "datetime"}
                 - {label: "Latest Date", name: "date-last", widget: "datetime"}
                 - {label: "description", name: "about", widget: "string"}
                 - {label: "Name", default: "Site 2", name: "textname", widget: "hidden"}
            
