# config.yml

backend:
 name: git-gateway
 branch: master # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

media_library:
 name: 'media_library'

collections:
  - name: 'sites'
    label: 'Sites'
    files:
      - label: "Site 1"
        folder: '_data/'
        file: "site.yml"
        fields:
          - label: "Site 1"
            name: "site1"
            widget: "string"
