# config.yml




backend:
 name: git-gateway
 branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
media_library: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
     - { name: Title }
